/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_joogie_prover_Z3ProverEx */
#ifndef _Included_org_joogie_prover_Z3ProverEx
#define _Included_org_joogie_prover_Z3ProverEx
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     org_joogie_prover_old_Z3ProverEx
	 * Method:    createContext
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_org_joogie_prover_old_Z3ProverEx_createContext(JNIEnv *, jobject);
	/*
	 * Class:     org_joogie_prover_old_Z3ProverEx
	 * Method:    deleteContext
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_org_joogie_prover_old_Z3ProverEx_deleteContext(JNIEnv *, jobject);
	/*
	 * Class:     org_joogie_prover_old_Z3ProverEx
	 * Method:    hasContext
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_org_joogie_prover_old_Z3ProverEx_hasContext(JNIEnv *, jobject);
	/*
	 * Class:     org_joogie_prover_old_Z3ProverEx
	 * Method:    check
	 * Signature: ()Z
	 */
	JNIEXPORT jint JNICALL Java_org_joogie_prover_old_Z3ProverEx_check(JNIEnv *, jobject, jstring);
	/*
	 * Class:     org_joogie_prover_old_Z3ProverEx
	 * Method:    push
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_org_joogie_prover_old_Z3ProverEx_push(JNIEnv *, jobject);
	/*
	 * Class:     org_joogie_prover_old_Z3ProverEx
	 * Method:    pop
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_org_joogie_prover_old_Z3ProverEx_pop(JNIEnv *, jobject);
	/*
	 * Class:     org_joogie_prover_old_Z3ProverEx
	 * Method:    getModel
	 * Signature: ()Z
	 */
	JNIEXPORT jstring JNICALL Java_org_joogie_prover_old_Z3ProverEx_getModel(JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
